config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'shared/micropost_form',        to: "microposts#new"
  post "likes/:micropost_id/create",  to: "likes#create"
  post "likes/:micropost_id/destroy", to: "likes#destroy"
  resources :users,                   only: [:show, :index]
  resources :microposts,              except: [:edit, :update] do
    resources :comments,              only: [:create, :destroy]
  end
  resources :relationships,           only: [:create, :destroy]
  resources :notifications,           only: :index
  resources :learnings
  post "/", to: "learning#create"
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :micropost, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/views/notifications/_notification.html.slim
- visitor = notification.visitor
- visited = notification.visited
div class="col-md-6 mx-auto"
  span
    = link_to user_path(visitor) do
      strong
        = visitor.name
    = "さんが"
    - case notification.action
    - when 'follow'
      = "あなたをフォローしました"
    - when 'like'
      = link_to 'あなたの投稿', notification.micropost, style: "font-weight: bold;"
      = "にいいねしました"
    - when 'comment'
      - if notification.micropost.user_id == visited.id
        = link_to "あなたの投稿", notification.micropost, style: "foot-weight: bold"
      - else
        span
          = link_to micropost_path(notification.micropost) do
            strong
              = notification.micropost.user.name + "さんの投稿"
      = "にコメントしました"
div class="small text-muted text-right"
  = time_ago_in_words(notification.created_at).upcase
hr

app/views/notifications/index.html.slim
- notifications = @notifications.where.not(visitor_id: current_user.id)
- if notifications.exists?
  = render notifications
  = paginate notifications
-else
  p
    |通知はありません