config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :omniauth_callbacks => "users/omniauth_callbacks",
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'shared/micropost_form',        to: "microposts#new"
  post "likes/:micropost_id/create",  to: "likes#create"
  post "likes/:micropost_id/destroy", to: "likes#destroy"
  resources :users,                   only: [:show, :index]
  resources :microposts,              except: [:edit, :update] do
    resources :comments,              only: [:create, :destroy]
  end
  resources :relationships,           only: [:create, :destroy]
  resources :notifications,           only: :index
  resources :learnings
  post "/", to: "learning#create"
end

app/views/layouts/_footer.html.slim
footer.footer.container
  small
    |  The CloneApp by 
    a[href="https://twitter.com/taro89apo"]
      | Takumi Kobayashi
    div
      = link_to '利用規約', page_path('terms')
  nav
    ul
      li
        - if user_signed_in?
          = link_to new_micropost_path, class: "btn btn-lg btn-primary" do
            i.fas.fa-camera

app/views/layouts/_header.html.slim
nav.navbar.fixed-top.navbar-expand-lg.navbar-light.header
  .container
    .navbar-brand.mb-3
      = link_to 'Studiary', root_path, id: "logo", class: "text-white display-3"
    / button.navbar-toggler type="button" data-toggle="collapse" data-target="#List"
    /   span.navbar-toggler-icon
    .collapse.navbar-collapse#List
      - if user_signed_in?
        ul.navbar-nav.mr-auto
          li.search
            = search_form_for @search, url: microposts_path do |f|
              = f.text_field :content_or_user_name_cont ,placeholder: '検索：名前/投稿内容'
        ul.navbar-nav
          li.nav-item.dropdown
            a class="nav-link bg-secondary p-0" id="#List" role="button" data-toggle="dropdown"
              span.navbar-toggler-icon
            .dropdown-menu aria-labelledby="List"
              .dropdown-item.pl-1
                = link_to 'マイページ', current_user, class: "d-block", data: { turbolinks: :false }
              .dropdown-item.pl-1
                = link_to '通知', notifications_path, class: "d-block", data: { turbolinks: :false }
              .divider
              .dropdown-item.pl-2
                = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "d-block"
      - else
        li
          = link_to 'サインアップ', new_user_registration_path
        li
          = link_to 'ログイン', new_user_session_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield
    script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
  footer.nav.navbar
    = render 'layouts/footer'